image: python:3.4

before_script:
  - pip install pytest

build_job:
  script:
    - pip wheel .
  stage: build

test_job_py34:
  script:
    - py.test
  stage: test


test_job_py35:
  image: python:3.5
  script:
    - py.test
  stage: test
